### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [tulioribeiro/zsh-tcr-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by tulioribeiro** [comment]
Hey @unixorn 

Sorry for the delay! I've just updated zsh-tcr-theme with the license file you requested. Thanks for your patience!

**Comment by unixorn** [comment]
NP, adding in today's update
